### ISSUE TITLE
It was not supported by linearmodel.

### ISSUE THREAD

**Issue by jefeerzhang** [mwburke/stargazer#68] opened 2021-03-26 05:33 UTC
import numpy as np
from statsmodels.datasets import grunfeld
data = grunfeld.load_pandas().data
data.year = data.year.astype(np.int64)
from linearmodels import PanelOLS
# MultiIndex, entity - time
data = data.set_index(['firm','year'])
mod = PanelOLS.from_formula('invest ~ value + capital + EntityEffects+TimeEffects', data)
res = mod.fit(cov_type='clustered', cluster_entity=True)
from stargazer.stargazer import Stargazer
st = Stargazer(res)

**Comment by toobaz** [comment] 2021-03-26 07:47
Duplicate of #26 I think.

**Closed by toobaz** 2021-03-26 07:47 UTC
