### ISSUE TITLE
Issues creating a table of logistic regressions

### ISSUE THREAD

**Issue by spfraib** [mwburke/stargazer#52] opened 2020-06-14 02:18 UTC
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-23-b6428c155fe6> in <module>
      1 for label in labels:
      2     print(label)
----> 3     stargazer = Stargazer(models[label])
      4     stargazer.render_html()

/scratch/spf248/pyenv/py3.7/lib/python3.7/site-packages/stargazer/stargazer.py in __init__(self, models)
     29         self.models = models
     30         self.num_models = len(models)
---> 31         self.extract_data()
     32         self.reset_params()
     33 

/scratch/spf248/pyenv/py3.7/lib/python3.7/site-packages/stargazer/stargazer.py in extract_data(self)
     94         self.model_data = []
     95         for m in self.models:
---> 96             self.model_data.append(self.extract_model_data(m))
     97 
     98         covs = []

/scratch/spf248/pyenv/py3.7/lib/python3.7/site-packages/stargazer/stargazer.py in extract_model_data(self, model)
    109         data['conf_int_low_values'] = model.conf_int()[0]
    110         data['conf_int_high_values'] = model.conf_int()[1]
--> 111         data['r2'] = model.rsquared
    112         data['r2_adj'] = model.rsquared_adj
    113         data['resid_std_err'] = sqrt(model.scale)

/share/apps/anaconda3/2019.10/lib/python3.7/site-packages/statsmodels/base/wrapper.py in __getattribute__(self, attr)
     33             pass
     34 
---> 35         obj = getattr(results, attr)
     36         data = results.model.data
     37         how = self._wrap_attrs.get(attr)

AttributeError: 'LogitResults' object has no attribute 'rsquared'`

**Comment by toobaz** [comment] 2020-06-14 09:02
Duplicate of #24

**Closed by toobaz** 2020-06-14 09:02 UTC

**Comment by toobaz** [comment] 2020-06-14 09:04
(We should be soon producing a release with this and other improvements)
