### ISSUE TITLE
Minor issue regarding LaTeX format

### ISSUE THREAD

**Issue by MarcoYou** [mwburke/stargazer#72] opened 2021-04-18 16:28 UTC
This is the output of my regression results displayed in LaTeX format using your Stargazer library

'\\begin{table}[!htbp] \\centering\n\\begin{tabular}{@{\\extracolsep{5pt}}lc}\n\\\\[-1.8ex]\\hline\n\\hline \\\\[-1.8ex]\n& \\multicolumn{1}{c}{\\textit{Dependent variable:}} \\\n\\cr \\cline{1-2}\n\\\\[-1.8ex] & (1) \\\\\n\\hline \\\\[-1.8ex]\n C(Interval)[T.10] & 6.703$^{***}$ \\\\\n  & (2.345) \\\\\n C(Interval)[T.11] & 9.415$^{***}$ \\\\\n  & (2.814) \\\\\n C(Interval)[T.12] & 16.132$^{***}$ \\\\\n  & (2.860) \\\\\n C(Interval)[T.13] & 16.612$^{***}$ \\\\\n  & (2.386) \\\\\n C(Interval)[T.14] & 15.988$^{***}$ \\\\\n  & (2.413) \\\\\n C(Interval)[T.15] & 13.337$^{***}$ \\\\\n  & (2.743) \\\\\n C(Interval)[T.16] & 20.233$^{***}$ \\\\\n  & (2.889) \\\\\n C(Interval)[T.17] & 35.098$^{***}$ \\\\\n  & (3.311) \\\\\n C(Interval)[T.18] & 17.979$^{***}$ \\\\\n  & (2.267) \\\\\n C(Interval)[T.19] & 5.698$^{***}$ \\\\\n  & (1.992) \\\\\n C(Interval)[T.1] & -1.479$^{}$ \\\\\n  & (2.464) \\\\\n C(Interval)[T.20] & 1.883$^{}$ \\\\\n  & (1.917) \\\\\n C(Interval)[T.21] & 0.774$^{}$ \\\\\n  & (2.040) \\\\\n C(Interval)[T.22] & -0.032$^{}$ \\\\\n  & (1.755) \\\\\n C(Interval)[T.23] & -1.080$^{}$ \\\\\n  & (3.540) \\\\\n C(Interval)[T.2] & -1.705$^{}$ \\\\\n  & (1.294) \\\\\n C(Interval)[T.3] & -1.990$^{}$ \\\\\n  & (1.443) \\\\\n C(Interval)[T.4] & -1.854$^{}$ \\\\\n  & (1.474) \\\\\n C(Interval)[T.5] & -1.762$^{}$ \\\\\n  & (1.321) \\\\\n C(Interval)[T.6] & 0.854$^{}$ \\\\\n  & (2.161) \\\\\n C(Interval)[T.7] & 26.739$^{***}$ \\\\\n  & (3.236) \\\\\n C(Interval)[T.8] & 34.671$^{***}$ \\\\\n  & (2.645) \\\\\n C(Interval)[T.9] & 12.557$^{***}$ \\\\\n  & (2.074) \\\\\n C(Weekend)[T.1]:C(Interval)[0] & 0.133$^{}$ \\\\\n  & (0.556) \\\\\n C(Weekend)[T.1]:C(Interval)[10] & -0.827$^{}$ \\\\\n  & (3.674) \\\\\n C(Weekend)[T.1]:C(Interval)[11] & -2.195$^{}$ \\\\\n  & (2.928) \\\\\n C(Weekend)[T.1]:C(Interval)[12] & -12.281$^{***}$ \\\\\n  & (2.307) \\\\\n C(Weekend)[T.1]:C(Interval)[13] & -12.891$^{***}$ \\\\\n  & (3.196) \\\\\n C(Weekend)[T.1]:C(Interval)[14] & -7.909$^{**}$ \\\\\n  & (3.198) \\\\\n C(Weekend)[T.1]:C(Interval)[15] & -11.773$^{***}$ \\\\\n  & (2.810) \\\\\n C(Weekend)[T.1]:C(Interval)[16] & -15.694$^{***}$ \\\\\n  & (2.859) \\\\\n C(Weekend)[T.1]:C(Interval)[17] & -25.585$^{***}$ \\\\\n  & (3.346) \\\\\n C(Weekend)[T.1]:C(Interval)[18] & -13.641$^{***}$ \\\\\n  & (2.007) \\\\\n C(Weekend)[T.1]:C(Interval)[19] & -4.874$^{***}$ \\\\\n  & (1.157) \\\\\n C(Weekend)[T.1]:C(Interval)[1] & 0.108$^{}$ \\\\\n  & (0.385) \\\\\n C(Weekend)[T.1]:C(Interval)[20] & -2.335$^{***}$ \\\\\n  & (0.691) \\\\\n C(Weekend)[T.1]:C(Interval)[21] & -0.727$^{}$ \\\\\n  & (0.720) \\\\\n C(Weekend)[T.1]:C(Interval)[22] & -0.051$^{}$ \\\\\n  & (0.410) \\\\\n C(Weekend)[T.1]:C(Interval)[23] & 0.555$^{}$ \\\\\n  & (0.436) \\\\\n C(Weekend)[T.1]:C(Interval)[2] & 0.876$^{}$ \\\\\n  & (0.615) \\\\\n C(Weekend)[T.1]:C(Interval)[3] & 1.087$^{*}$ \\\\\n  & (0.556) \\\\\n C(Weekend)[T.1]:C(Interval)[4] & 0.255$^{}$ \\\\\n  & (0.675) \\\\\n C(Weekend)[T.1]:C(Interval)[5] & 0.577$^{}$ \\\\\n  & (0.984) \\\\\n C(Weekend)[T.1]:C(Interval)[6] & -1.419$^{}$ \\\\\n  & (1.924) \\\\\n C(Weekend)[T.1]:C(Interval)[7] & -26.639$^{***}$ \\\\\n  & (3.009) \\\\\n C(Weekend)[T.1]:C(Interval)[8] & -31.479$^{***}$ \\\\\n  & (2.611) \\\\\n C(Weekend)[T.1]:C(Interval)[9] & -10.904$^{***}$ \\\\\n  & (3.077) \\\\\n Intercept & 4.599$^{}$ \\\\\n  & (3.524) \\\\\n Num_Transfer & -2.335$^{**}$ \\\\\n  & (0.977) \\\\\n Req_1D & -0.020$^{}$ \\\\\n  & (0.026) \\\\\n Req_2H & 0.022$^{***}$ \\\\\n  & (0.005) \\\\\n Req_DP & -0.006$^{}$ \\\\\n  & (0.005) \\\\\n TopSpeed & -0.348$^{}$ \\\\\n  & (0.546) \\\\\n\\hline \\\\[-1.8ex]\n Observations & 504 \\\\\n $R^2$ & 0.900 \\\\\n Adjusted $R^2$ & 0.888 \\\\\n Residual Std. Error & 4.474(df = 451)  \\\\\n F Statistic & 75.550$^{***}$ (df = 52.0; 451.0) \\\\\n\\hline\n\\hline \\\\[-1.8ex]\n\\textit{Note:} & \\multicolumn{1}{r}{$^{*}$p$<$0.1; $^{**}$p$<$0.05; $^{***}$p$<$0.01} \\\\\n\\end{tabular}\n\\end{table}'

It seems like it's duplicating each and every anti-slashes "\"

**Comment by toobaz** [comment] 2021-04-18 19:54
Duplicate of #63

**Closed by toobaz** 2021-04-18 19:54 UTC
